name: Terratest

on:
  push:
    branches: [main]

jobs:
  terratest:
    runs-on: ubuntu-latest # self-hosted
    # container: hashicorp/terraform:latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.1.0"
      - name: Check go version
        run: go version
