name: Lint
on:
  workflow_call
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Install modules
      run: npm install -g eslint
    - name: Run ESLint
      run: eslint index.js --fix #To display output on console
    - name: Generate Report
      run: eslint index.js --fix -f checkstyle > eslint.xml #To create report which will be use by checkstyle plugin