name: Lint
on:
  workflow_call
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Run Eslint
      run: yarn
      run: yarn eslint . --ext .js -c .eslintrc.js --fix #To display output on console
      run: yarn eslint . --ext .js -c .eslintrc.js --fix -f checkstyle > eslint.xml #To create report which will be use by checkstyle plugin
