name: Lint
on:
  workflow_call
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Install modules
      run: npm install -g eslint
    - name: Run ESLint
      run: eslint . --ext .js #To display output on console
